application: whos-shout-is-it
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.2"

handlers:
- url: /web/stylesheets
  static_dir: web/stylesheets

- url: /web/images
  static_dir: web/images

- url: /web/js
  static_dir: web/js

- url: /admin/.*
  script: app_admin.app
  login: admin

- url: /.*
  script: whos_shout_auth.app
  login: required